// É dessa forma que se comenta algo sem aparecer no javascript
console.log('OLá mundo!');// Aqui tem ouro comentario
console.log('Linha 1');
console.log('Linha 2');
console.log('Linha 3!');
console.log('Linha 4');
// Vai ser ignorado novamente pois é um comentario
// esses dois traços é um comentario da linha só consegue comentar uma linha de codigo

/*Um bloco de codigo, permite comentar em grande escala conteudos */


